#!/usr/bin/env python3
"""Regenerates images/sheet-music-data.js from images/*.png.

Why this exists
----------------
The sheet music PDF fallback (used when a browser can't open the native
print dialog, e.g. iOS Edge/Chrome, or when this site is opened via
file://) needs each sheet music image available as an in-memory base64
data URI:

  * The source PNGs are saved in palette/indexed-color mode, which
    jsPDF's built-in PNG decoder mishandles (renders solid black blocks).
    Re-encoding as true-color RGB here fixes that at the source, so the
    PDF code never has to rasterize through a <canvas> to work around it.
  * When this site is opened directly from disk (file://) instead of a
    web server, Chrome/Edge treat every local file as its own opaque
    origin. That means any attempt to read an <img>'s pixels back out via
    <canvas>.toDataURL() (or fetch()) throws "Tainted canvases may not be
    exported" / is blocked outright. A <script src="..."> tag, however,
    loads fine from file://, so baking the image bytes into a plain .js
    file sidesteps both problems at once.

Usage
-----
Run this from the repo root whenever a sheet music image in images/ is
added, removed, or replaced:

    python tools/generate-sheet-music-data.py

Requires Pillow (`pip install pillow`). Not needed to run the site itself
-- images/sheet-music-data.js is a generated, checked-in artifact.
"""

import base64
import io
import os

from PIL import Image

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMAGES_DIR = os.path.join(REPO_ROOT, "images")
OUTPUT_PATH = os.path.join(IMAGES_DIR, "sheet-music-data.js")


def build_data_uri(png_path):
    im = Image.open(png_path)
    # Drop palette/indexed-color mode (and any CMYK/etc oddities) in favor
    # of plain true-color, with alpha preserved if the source had it.
    if im.mode not in ("RGB", "RGBA"):
        im = im.convert("RGBA" if "transparency" in im.info or im.mode in ("P", "LA") else "RGB")
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    encoded = base64.b64encode(buf.getvalue()).decode("ascii")
    return "data:image/png;base64," + encoded


def main():
    entries = []
    for name in sorted(os.listdir(IMAGES_DIR)):
        if not name.lower().endswith(".png"):
            continue
        call_id = name[:-4]
        data_uri = build_data_uri(os.path.join(IMAGES_DIR, name))
        entries.append((call_id, data_uri))

    lines = []
    lines.append("// AUTO-GENERATED by tools/generate-sheet-music-data.py -- do not edit by hand.")
    lines.append("// Re-run that script after adding/changing/removing a file in images/*.png.")
    lines.append("window.BUGLE_SHEET_MUSIC_DATA = {")
    for call_id, data_uri in entries:
        lines.append('  "%s": "%s",' % (call_id, data_uri))
    lines.append("};")

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    total_bytes = os.path.getsize(OUTPUT_PATH)
    print("Wrote %s (%d calls, %.1f KB)" % (OUTPUT_PATH, len(entries), total_bytes / 1024.0))


if __name__ == "__main__":
    main()
